theme: jekyll-theme-dinky
title: [2020 Collegeville Workshop on Scientific Software - Developer Productivity (CW20)]
description: [CW20 brings community members together to advance developer productivity for scientific software]
