theme: jekyll-theme-dinky
title: [2020 Collegeville Workshop on Scientific Software - Developer Productivity (CWSS20-DP)]
description: [CWSS20-DP brings community members together to advance developer productivity for scientific software]
